language: cpp
sudo: required
services: docker

addons:
  apt:
    packages:
    - protobuf-compiler
    - libprotobuf-dev
    - libutempter-dev
    - bsdutils			# for script, for smoke test

before_install:
  - git fetch --tags --unshallow

script:
  - ./autogen.sh
  - ./configure --enable-compile-warnings=error --enable-examples
  - make distcheck

notifications:
  irc: "chat.freenode.net#mosh"
